language: java

sudo: false

jdk:
  - openjdk8

install:
  - export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
  - mvn install -DskipTests -Dgpg.skip=true

script:
  - export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
  - mvn verify -Dgpg.skip=true

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

cache:
  directories:
    - $HOME/.m2